from .dim_tiempo import DimTiempo
from .dim_institucion import DimInstitucion
from .dim_estudiante import DimEstudiante
from .dim_docente import DimDocente
from .dim_modulo import DimModulo
from .dim_origen import DimOrigenDocumental
from .user import User
from .fact_rendimiento import FactRendimientoAcademico
from .fact_financiero import FactSituacionFinanciera